// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5IS8U0yndI1CXfXdfXD2ZNbOpWfXyhRk',
    appId: '1:538899091941:web:e1d8240b97047b999c1f0c',
    messagingSenderId: '538899091941',
    projectId: 'pokedex-flutter-4c2b8',
    authDomain: 'pokedex-flutter-4c2b8.firebaseapp.com',
    storageBucket: 'pokedex-flutter-4c2b8.appspot.com',
    measurementId: 'G-V0YRRN8YD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsVz_3PWDKY_XmNhKCV9-jqaojDhAidRs',
    appId: '1:538899091941:android:9a78f9c9abd578019c1f0c',
    messagingSenderId: '538899091941',
    projectId: 'pokedex-flutter-4c2b8',
    storageBucket: 'pokedex-flutter-4c2b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqa-OfD_uXOi3qg6MnRI9mmO4vjS5YqK0',
    appId: '1:538899091941:ios:231ed3411bfc0f259c1f0c',
    messagingSenderId: '538899091941',
    projectId: 'pokedex-flutter-4c2b8',
    storageBucket: 'pokedex-flutter-4c2b8.appspot.com',
    iosClientId: '538899091941-fs8df7chmgbp0des4bl47h8vim7afd60.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqa-OfD_uXOi3qg6MnRI9mmO4vjS5YqK0',
    appId: '1:538899091941:ios:ce7d530461e1aa699c1f0c',
    messagingSenderId: '538899091941',
    projectId: 'pokedex-flutter-4c2b8',
    storageBucket: 'pokedex-flutter-4c2b8.appspot.com',
    iosClientId: '538899091941-j3chrc8khisjfm94kko8mfdaqrqq4i3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexMobile.RunnerTests',
  );
}
